// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApFifo7EAejRsAFB2cazxzD_hDoVJ7YjM',
    appId: '1:152391570514:web:56e0b097049e62773d3b8b',
    messagingSenderId: '152391570514',
    projectId: 'ruhrkulturerlebnisapp',
    authDomain: 'ruhrkulturerlebnisapp.firebaseapp.com',
    databaseURL: 'https://ruhrkulturerlebnisapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhrkulturerlebnisapp.appspot.com',
    measurementId: 'G-XYNJR46933',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2xN5NYSk3w24KAtC54orwn90oJRENAI',
    appId: '1:152391570514:android:159a60b99983bded3d3b8b',
    messagingSenderId: '152391570514',
    projectId: 'ruhrkulturerlebnisapp',
    databaseURL: 'https://ruhrkulturerlebnisapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhrkulturerlebnisapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBNcIiwS3eVMksy0_spzjEP6fRj1z4Bc',
    appId: '1:152391570514:ios:65dfffc6f789e08e3d3b8b',
    messagingSenderId: '152391570514',
    projectId: 'ruhrkulturerlebnisapp',
    databaseURL: 'https://ruhrkulturerlebnisapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhrkulturerlebnisapp.appspot.com',
    iosClientId: '152391570514-mt2sagbassfe1fn9kk8k75fh3qsq8ase.apps.googleusercontent.com',
    iosBundleId: 'com.filmprojekt1.ruhrkulturerlebnisapp.reka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBNcIiwS3eVMksy0_spzjEP6fRj1z4Bc',
    appId: '1:152391570514:ios:3a2f0ea940c5cf7d3d3b8b',
    messagingSenderId: '152391570514',
    projectId: 'ruhrkulturerlebnisapp',
    databaseURL: 'https://ruhrkulturerlebnisapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ruhrkulturerlebnisapp.appspot.com',
    iosClientId: '152391570514-cs9t7319e51ppnu27p9fuk9au5k65ti2.apps.googleusercontent.com',
    iosBundleId: 'com.filmprojekt1.ruhrkulturerlebnisapp.reka.RunnerTests',
  );
}
